all:
	(cd exo1; make all)
	(cd exo2; make all)
	(cd exo3; make all)
	(cd exo4; make all)
	(cd exo5; make all)

clean:
	(cd exo1; make clean)
	(cd exo2; make clean)
	(cd exo3; make clean)
	(cd exo4; make clean)
	(cd exo5; make clean)